### ISSUE TITLE
whitespaces in filenames

### ISSUE THREAD

**Issue by barkonar** [hoegaarden/pgpass#12]
Hi,

Files with tests contain whitespaces in names. Would it be possible to replace it with other char e.g. underscore? I'd appreciate it as it generates a lot of trouble (I have a complicated build process that uses awk and whitespaces cause misaligns).

Best regards,
Bartek

**Comment by hoegaarden** [comment]
Hey @barkonar .

I am not sure what you actual problem is, maybe it's worth describing your problems in more detail and where and why this module exactly breaks your process?

Generally spoken, I think it is definitely a bug if systems break on spaces (or other "special" chars) in file names. However, I am also aware that you might not always be able to fix those issues (easily).

Anyhow, would it help when I `.npmignore` the tests? But again, I still think that is a bug on your build system which is worth fixing ...

Bye

**Comment by hoegaarden** [comment]
Hey @barkonar ... do you have any update / more input on your problem?

**Comment by barkonar** [comment]
Hi @hoegaarden,

Sorry for late answer, I've missed your previous message. 

I'm afraid I can't explain in details the building process (corporation secrets ;-) ), but even if I could do it it would take a long time... In general the point is that building process in some point uses awk for parsing file list. By default it uses space as a separator of column, which unfortunately I can't change. So when I have a file e.g. "#1 de-escaping.js" awk returns "#1" as a file name. 

The perfect solution would be to rename such files to e.g: #1_de-escaping.js. There are only 4 files with whitespaces in tests. As far as I know it should not affect anything else.

As far as .npmignore is concerned it should also solve the problem, as the files would still exist on repository for developers, but wouldn't be downloaded by npm while normal install. At least I expect that this works this way ;-)

BR
B.

**Comment by hoegaarden** [comment]
Hey @barkonar 
I removed the tests from the module in `1.0.2`, I hope that fixes your problem.
Bye.
